import Head from 'next/head'
import Image from 'next/image'
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utilits/requests";

// Ленивая под грузка изображений
// Что такое реквизит? - это компонент который можно неоднократно использовать.

export default function Home({results}) {
    console.log('results', results);

  return (
    <div className="">
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {/* Header */}
    <Header />

    {/* Nav */}
    <Nav />

    {/* Results */}

        <Results results={results}/>
    </div>
  )
}

export async function getServerSideProps(context) {
    const genre = context.query.genre;

    const request = await fetch(`https://api.themoviedb.org/3/${
        requests[genre]?.url || requests.fetchTrending.url
    }`
    ).then(res => res.json());

    console.log(request);

    return {
        props: {
            results: request.results,
        }
    }
}
